"""Batch ROI editor: open roi_editor.py for every recording folder under a root.

Walks the root the same way run_intermingle_rs.py does (any folder that contains
at least two TIFFs is a recording), then opens the ROI editor with ALL discovered
folders loaded as pages.  Navigate pages with n / p, press c to copy the previous
page's ROI layout onto the current one, s to save the current page, ctrl+s to save
every page you changed, or S to save all of them.

Each ROI set is written to  <roi_set_dir>/<key>.yaml  where the key is the last
three path components of the recording folder (e.g. 260611_R1_t1).  That key is
the same one run_intermingle_rs.py uses when its  roi_set_dir  is set to the same
directory, so the two scripts stay in sync without manual renaming.

Two directories, on purpose
---------------------------
``roi_seed_dir`` is where each page's STARTING layout is read from and is never
written to; ``roi_set_dir`` is where 's' / 'S' / ctrl+s write.  They are separate so
the verified sets in ``roi_sets/rebuilt`` (regenerated by rebuild_roi_sets.py: a pure
Lambda rescale of the baseline atlas, bilaterally symmetric by construction) can be
opened and inspected page by page without a stray keypress overwriting them.  Anything
you adjust lands in ``roi_sets/reviewed`` instead, and the reference stays intact.

Precedence per page: your own saved set in ``roi_set_dir`` first (so re-running resumes
your edits), then ``roi_seed_dir``, then the profile atlas.  'r' resets the page to the
layout it opened with; ctrl+r resumes from disk, which now falls back to the reference
set -- the "discard my changes and go back to the rebuilt layout" button.

Set ``roi_seed_dir`` to None for the old single-directory behaviour.

Run it (--no-capture-output keeps prints live during decoding):
    conda run --no-capture-output -n letizia python batch_roi_select.py
    conda run --no-capture-output -n letizia python batch_roi_select.py --folder "\\\\host\\share\\260611"
    conda run --no-capture-output -n letizia python batch_roi_select.py --no-load-existing
    # inspect the rebuilt sets, write nowhere near them:
    conda run --no-capture-output -n letizia python batch_roi_select.py \
        --roi-seed-dir roi_sets/rebuilt --roi-set-dir roi_sets/reviewed

From VS Code: the "Batch ROI select (batch_roi_select.py)" launch config.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

from roi_editor import (
    MIN_LAMBDA_OFFSET,
    ROIEditor,
    sessions_from_folders,
)
from run_intermingle_rs import discover_recordings
from wfci import get_profile

# ---------------------------------------------------------------------------
# Edit this section to run without CLI flags.
# ---------------------------------------------------------------------------
RUN_CONFIG: dict[str, Any] = {
    # Root folder: every subfolder that holds at least 2 TIFFs becomes one page.
    "folder": r"F:\WF_2026\starting",
    "pattern": "*.tif",
    # Profile whose atlas is the starting box layout and whose downsample chain
    # sets the preview grid.  Must match the profile used in run_intermingle_rs.py.
    "profile": "cortical_gsr",
    # "auto" picks the dimmer interleaved group as GCaMP (reflectance is brighter).
    "channel_order": "auto",
    # Frames to average into the preview (1 = first image only; 5-20 = less noisy).
    "preview_frames": 1,
    # Fallback Bregma in full-resolution (doubled) coordinates, used when a page
    # has no per-recording ROI set yet.
    "bregma_row": 121,
    "bregma_col": 134,
    # Bregma -> Lambda distance in final-grid rows: the scale reference for the
    # editor's rescaling knob.
    "lambda_offset": 55,
    # False (default): rescaling moves box CENTRES but keeps each box's pixel area
    # fixed -- noise stays comparable across animals.  True = full similarity transform.
    "lambda_scales_box_size": False,
    # Where ROI sets are WRITTEN.  The filenames (<key>.yaml) are shared with
    # run_intermingle_rs.py -- point its roi_set_dir here and it picks them up.
    # Kept separate from roi_seed_dir so reviewing the rebuilt sets cannot damage them.
    "roi_set_dir": r"roi_sets/reviewed",
    # Read-only starting layouts: the sets regenerated by rebuild_roi_sets.py as a pure
    # Lambda rescale of the baseline atlas.  Each file carries its own bregma_row /
    # bregma_col / lambda_row_offset, so a page opens exactly as rebuilt and at scale
    # 1.000x -- the rescale knob starts neutral instead of stretching it again.
    # None = read starting layouts from roi_set_dir (the old single-directory behaviour).
    "roi_seed_dir": r"roi_sets/rebuilt",
    # Filename for the single shared file written by the 'w' key.
    "shared_name": "shared_roi_set.yaml",
    # True: re-open any already-saved <key>.yaml as the starting layout for that
    # page, so editing continues from where it left off.
    "load_existing": True,
    # Seed EVERY page from this one file instead of the profile atlas.  None = atlas.
    "start_from": None,
    "prefer_cli_args": True,
}


def parse_args(defaults: dict[str, Any]) -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Batch ROI editor for all recording folders.")
    p.add_argument("--folder", default=defaults["folder"],
                   help="Root folder; every subfolder holding TIFFs becomes one page.")
    p.add_argument("--pattern", default=defaults["pattern"], help="TIFF glob.")
    p.add_argument("--roi-set-dir", default=defaults["roi_set_dir"],
                   help="Where ROI sets are written.")
    p.add_argument("--roi-seed-dir", default=defaults["roi_seed_dir"],
                   help="Read-only directory of starting layouts (e.g. roi_sets/rebuilt). "
                        "Saves still go to --roi-set-dir.")
    p.add_argument("--shared-name", default=defaults["shared_name"])
    p.add_argument("--bregma-row", type=int, default=defaults["bregma_row"])
    p.add_argument("--bregma-col", type=int, default=defaults["bregma_col"])
    p.add_argument("--lambda-offset", type=int, default=defaults["lambda_offset"])
    p.add_argument("--preview-frames", type=int, default=defaults["preview_frames"])
    p.add_argument("--start-from", default=defaults["start_from"],
                   help="Seed every page from this ROI set file.")
    p.add_argument("--no-load-existing", dest="load_existing", action="store_false",
                   default=defaults["load_existing"],
                   help="Ignore ROI sets already in --roi-set-dir.")
    ns = p.parse_args()
    ns.profile = defaults["profile"]
    ns.channel_order = defaults["channel_order"]
    ns.lambda_scales_box_size = bool(defaults["lambda_scales_box_size"])
    return ns


def build_runtime_args(config: dict[str, Any] | None = None) -> argparse.Namespace:
    config = dict(RUN_CONFIG if config is None else config)
    if bool(config.get("prefer_cli_args", True)) and len(sys.argv) > 1:
        return parse_args(defaults=config)
    return argparse.Namespace(
        folder=config["folder"],
        pattern=config["pattern"],
        profile=config["profile"],
        channel_order=config["channel_order"],
        preview_frames=config["preview_frames"],
        bregma_row=config["bregma_row"],
        bregma_col=config["bregma_col"],
        lambda_offset=config["lambda_offset"],
        lambda_scales_box_size=bool(config["lambda_scales_box_size"]),
        roi_set_dir=config["roi_set_dir"],
        roi_seed_dir=config["roi_seed_dir"],
        shared_name=config["shared_name"],
        load_existing=bool(config["load_existing"]),
        start_from=config["start_from"],
    )


def main() -> None:
    args = build_runtime_args()

    if args.lambda_offset < MIN_LAMBDA_OFFSET:
        raise ValueError(
            f"lambda_offset={args.lambda_offset} is below the minimum "
            f"{MIN_LAMBDA_OFFSET} px (too short to be a usable scale ruler)."
        )

    profile = get_profile(args.profile)
    default_boxes = dict(profile.atlas)

    recordings = discover_recordings(args.folder, args.pattern)
    if not recordings:
        raise FileNotFoundError(
            f"No folder holding at least 2 {args.pattern!r} images found at or "
            f"below {args.folder!r}."
        )

    print(f"Root    : {args.folder}")
    print(f"Found   : {len(recordings)} recording folder(s)")
    print(f"Profile : {profile.name} ({profile.n_rois} ROIs: {profile.labels})")
    print(f"Writes  : {args.roi_set_dir}  (per page on 's' / 'S' / ctrl+s)")

    # Say plainly how many pages will actually find a starting layout, and where from.
    # Getting this wrong is silent -- the page just opens on the atlas instead -- so it
    # is worth one directory listing at startup.
    if args.roi_seed_dir:
        seed_dir = Path(args.roi_seed_dir)
        if not seed_dir.is_dir():
            raise FileNotFoundError(
                f"roi_seed_dir {args.roi_seed_dir!r} does not exist. Point it at a "
                f"directory of ROI sets (e.g. roi_sets/rebuilt, written by "
                f"rebuild_roi_sets.py), or set it to None to seed from the profile atlas."
            )
        print(f"Reads   : {seed_dir}  (read-only reference layouts, never written to)")
    if args.load_existing:
        print("Starting layout per page: your own saved set in "
              f"{args.roi_set_dir}"
              + (f", else {args.roi_seed_dir}" if args.roi_seed_dir else "")
              + ", else the profile atlas.")

    # sessions_from_folders expects args.folders (a list of strings) and
    # args.manifest = None to select the folder-based path.
    args.folders = [str(r) for r in recordings]
    args.manifest = None

    sessions = sessions_from_folders(args, default_boxes)
    print(f"Sessions: {len(sessions)} -> {[s.key for s in sessions]}")

    # A page with no starting layout opened on the profile atlas instead -- worth
    # naming, because it looks identical to a page that loaded a set successfully.
    seeded = [s for s in sessions if s.has_own_set]
    print(f"Seeded  : {len(seeded)}/{len(sessions)} pages opened from an existing ROI set")
    if len(seeded) < len(sessions):
        missing = [s.key for s in sessions if not s.has_own_set]
        print(f"          on the profile atlas (no set found): "
              f"{missing[:8]}{' ...' if len(missing) > 8 else ''}")
    print(
        "\nOpening the editor window (may appear BEHIND this terminal).\n"
        "n / p  next / prev page  |  c  copy previous page's ROIs  |"
        "  s  save this page  |  S  save all  |  ctrl+s  save modified  |"
        "  w  shared file  |  q  quit",
        flush=True,
    )

    ROIEditor(sessions, args, profile.name).run()
    print("Editor closed.")


if __name__ == "__main__":
    main()
